### PR TITLE
Add docs for custom endpoints

### PR DESCRIPTION
**Pull request by JohnStarich**
Add docs for custom endpoints and fix some spelling and grammar.

Rendered README, for convenience: https://github.com/JohnStarich/convoy/blob/feature/document-custom-endpoints/README.md

### CODE REVIEW

**Comment by JohnStarich** [comment]
Hey @yasker! I had a few questions about the README, when you have a minute:

1. Looks like the README requires manual updates for version changes. If you want an automated "latest version" thing, I made one for my repo recently and I could add it here: https://github.com/johnstarich/bashtion#try-it
```bash
source <(curl -fsSL -H 'Accept: Accept: application/vnd.github.v3+json' https://api.github.com/repos/JohnStarich/bashtion/releases/latest | grep browser_download_url | cut -d '"' -f 4 | xargs curl -fsSL)
```
2. Is the second bullet point still correct? It sounds like it contradicts the third point:
```markdown
* NFS, EBS and DigitalOcean: The `-r/--reference` option instructs the `convoy delete` command to only delete the reference to the volume from the current host and leave the underlying files on [NFS server](https://github.com/rancher/convoy/blob/master/docs/vfs.md#delete) or [EBS volume](https://github.com/rancher/convoy/blob/master/docs/ebs.md#delete) unchanged. This is useful when the volume need to be reused later.
* [`docker rm -v`](https://github.com/rancher/convoy/blob/master/docs/docker.md#delete-container) would be treated as `convoy delete` with `-r/--reference`.
* If you use `--rm` with `docker run`, all volumes associated with the container would be deleted on exit in the same way as executing `docker rm -v`. See [Docker run reference](https://docs.docker.com/engine/reference/run/) for details.
```

**Comment by yasker** [comment]
@JohnStarich Thanks for the detailed update! It looks much nicer now. :)

1. I guess the manual update is fine. I always wanted MD file to be automatically updated for the latest version, or have a tag always pointed to the latest release. But seems either can be done.
2. The `volumes` I referred in the third point is the Docker volumes, not the real volume content in the system/disk/ebs. Maybe you can help on improving the wording on that as well? :wink:

Thanks again for so detailed doc update!

**Comment by JohnStarich** [comment]
@yasker No problem! I believe great docs drives higher adoption... and I couldn't help myself 😄

I've added an automatically updating release link and an automatic "latest release" download script. I also reworded that 3rd bullet point a little bit

**Comment by yasker** [comment]
@JohnStarich Sorry, seems I made typo in my comment. I meant it's ok for hardcode version number in the README.md for now. The script is nice but we still need to update the code to show the latest version anyway. So I think it's fine for now.

I think we're good to go once we dropped the last commit.

**Comment by JohnStarich** [comment]
@yasker Updated!

**Pull request merged**
