### PR TITLE
change uuid to name

### LINKED ISSUE #121: glusterfs.GlusterFSVolume doesn't have required field Name
My convoy-gluster container fails to mount on my dev box (starts up and mounts fine on all of my staging machines...), so I thought I would try out `rancher/convoy-agent:v0.7.0` to see if there had maybe been relevant fixes.

Looks like [GlusterFSVolume](https://github.com/rancher/convoy/blob/690f170961f007b02bc48e0cbe98d7335085386e/glusterfs/glusterfs.go#L79) should probably have a field `Name` which mirrors the `UUID`

```
Waiting for metadata
time="2016-05-13T02:46:33Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/16825/ns/mnt -F -- /var/lib/docker/aufs/mnt/18de0aba3a867d3fbf6d12ab5bde0bdf79fd9d9f7ac4bab351ae4f6da62c5f0e/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-ad135d13-c8b7-4083-8b71-079b75e23f30 -- /launch volume-agent-glusterfs-internal]"
Waiting for metadata
Registering convoy socket at /var/run/convoy-convoy-gluster.sock
time="2016-05-13T02:46:33Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
time="2016-05-13T02:46:33Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=vol1 glusterfs.servers=glusterfs]"
time="2016-05-13T02:46:33Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-ad135d13-c8b7-4083-8b71-079b75e23f30"
time="2016-05-13T02:46:33Z" level=info msg="Got: drivers [glusterfs]"
time="2016-05-13T02:46:33Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-gluster.sock daemon --driver-opts=glusterfs.defaultvolumepool=vol1 --driver-opts=glusterfs.servers=glusterfs --root=/var/lib/rancher/convoy/convoy-gluster-ad135d13-c8b7-4083-8b71-079b75e23f30 --drivers=glusterfs]"
time="2016-05-13T02:46:33Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-ad135d13-c8b7-4083-8b71-079b75e23f30" pkg=daemon
time="2016-05-13T02:46:33Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:vol1 glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-ad135d13-c8b7-4083-8b71-079b75e23f30"
time="2016-05-13T02:46:33Z" level=debug msg="Cleaning up environment..." pkg=daemon
time="2016-05-13T02:46:33Z" level=error msg="BUG: glusterfs.GlusterFSVolume doesn't have required field Name"
{
	"Error": "BUG: glusterfs.GlusterFSVolume doesn't have required field Name"
}
time="2016-05-13T02:46:33Z" level=info msg="convoy exited with error: exit status 1"
time="2016-05-13T02:46:33Z" level=info msg=Exiting.
```

### PR DESCRIPTION
**Pull request by mastertinner**
@yasker, can you please advise if this change fixes #121 and if it's a good idea to replace the `UUID` with `Name` or if we should rather have both?

### CODE REVIEW

**Comment by yasker** [comment]
Thanks @mastertinner I think it's good way to go.

The problem now is we don't have test cases for glusterfs, so we cannot say confidently things are fixed or not. We'd better find a way to validate the change.

**Comment by mastertinner** [comment]
@yasker how can I support there? It would be very helpful to me if this could get fixed.

**Comment by fbrbovic** [comment]
Any chance of this getting pulled in anytime soon , or should I start looking into compiling this on my own  ?

**Comment by mastertinner** [comment]
@fbrbovic I think the problem is that we have no way of testing it, so if you could compile it and see if it works as expected, that would be very helpful!

**Comment by fbrbovic** [comment]
I tried compiling it , but there is not much instructions on how it all goes together into a docker image, so I am not sure I did it.   Is ther instructions somewhere on how to build a convoy agent along with convoy so it can be used in rancher ?

**Comment by derDieDasJojo** [comment]
I compiled versision of convoy from the  [PR:change uuid to name](https://github.com/rancher/convoy/pull/134) using ```make```. Then copied the resulting ``bin/convoy`` into a fork of rancher/convoy-agent and build that. I published the modified [derdiedasjojo/convoy-agent](https://github.com/derDieDasJojo/convoy-agent) repo and also the [docker-files](https://hub.docker.com/r/derdiedasjojo/convoy-agent/builds/). Then I replaced the image for [convoy-gluster template](https://github.com/derDieDasJojo/community-catalog/blob/master/templates/convoy-gluster/1/docker-compose.yml) like this: `image: derdiedasjojo/convoy-agent:v0.9.0-fix121`

But the `gluster-convoy` Service continues to try starting and falls back to `stopped` with the following log:
```
15.7.2016 20:38:06Waiting for metadata
15.7.2016 20:38:06time="2016-07-15T18:38:06Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/21491/ns/mnt -F -- /var/lib/docker/overlay/bea8f485a053939f884e145752218952af012452f4e2f0b4120edbd7f55aeb2f/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-750dd9cb-0c6f-4831-8815-e14fba03b618 -- /launch volume-agent-glusterfs-internal]"
15.7.2016 20:38:06time="2016-07-15T18:38:06Z" level=warning msg="signal: killed"
15.7.2016 20:38:06time="2016-07-15T18:38:06Z" level=error msg="Failed to start (pid 21527) &libcontainer.Process{Args:[]string{\"/launch\", \"volume-agent-glusterfs-internal\"}, Env:[]string{\"CATTLE_CONFIG_URL=http://192.168.99.100:8080/v1\", \"HOSTNAME=bbf11d7801b1\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_3_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-volume-create_3\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DATA_2_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-data_2\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DAEMON_3_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-daemon_3\", \"CATTLE_ACCESS_KEY=333C50983BB8ABB9DCEB\", \"CATTLE_AGENT_INSTANCE_AUTH=Basic MzMzQzUwOTgzQkI4QUJCOURDRUI6WXdUTkRLVnlCWW1oTERkbzY3UWl5b3lORWhCbVFGbmdRUlk5cTdrUg==\", \"GLUSTERFS_GLUSTERFS_SERVER_2_NAME=/cattle/glusterfs_glusterfs-server_2\", \"GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_2_NAME=/cattle/glusterfs-server_glusterfs-volume-create_2\", \"GLUSTERFS_SERVER_3_NAME=/cattle/glusterfs-server_3\", \"GLUSTERFS_GLUSTERFS_SERVER_3_NAME=/cattle/glusterfs_glusterfs-server_3\", \"GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_3_NAME=/cattle/glusterfs-server_glusterfs-volume-create_3\", \"CATTLE_SECRET_KEY=YwTNDKVyBYmhLDdo67QiyoyNEhBmQFngQRY9q7kR\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DAEMON_2_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-daemon_2\", \"GLUSTERFS_SERVER_GLUSTERFS_DAEMON_3_NAME=/cattle/glusterfs-server_glusterfs-daemon_3\", \"GLUSTERFS_NAME=/cattle/glusterfs\", \"GLUSTERFS_SERVER_GLUSTERFS_DATA_3_NAME=/cattle/glusterfs-server_glusterfs-data_3\", \"PATH=/var/lib/rancher/convoy-agent:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"GLUSTERFS_SERVER_GLUSTERFS_DATA_2_NAME=/cattle/glusterfs-server_glusterfs-data_2\", \"GLUSTERFS_SERVER_1_NAME=/cattle/glusterfs-server_1\", \"PWD=/\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_1_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-volume-create_1\", \"SHLVL=1\", \"HOME=/root\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DATA_3_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-data_3\", \"CATTLE_URL=http://192.168.99.100:8080/v1\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DAEMON_1_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-daemon_1\", \"GLUSTERFS_SERVER_GLUSTERFS_DAEMON_1_NAME=/cattle/glusterfs-server_glusterfs-daemon_1\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_DATA_1_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-data_1\", \"GLUSTERFS_GLUSTERFS_SERVER_1_NAME=/cattle/glusterfs_glusterfs-server_1\", \"GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_1_NAME=/cattle/glusterfs-server_glusterfs-volume-create_1\", \"GLUSTERFS_SERVER_2_NAME=/cattle/glusterfs-server_2\", \"GLUSTERFS_SERVER_GLUSTERFS_DATA_1_NAME=/cattle/glusterfs-server_glusterfs-data_1\", \"GLUSTERFS_GLUSTERFS_SERVER_GLUSTERFS_VOLUME_CREATE_2_NAME=/cattle/glusterfs_glusterfs-server_glusterfs-volume-create_2\", \"GLUSTERFS_SERVER_GLUSTERFS_DAEMON_2_NAME=/cattle/glusterfs-server_glusterfs-daemon_2\", \"_=/var/lib/rancher/convoy-agent/share-mnt\"}, User:\"0:0\", Cwd:\"\", Stdin:(*os.File)(0xc820028108), Stdout:(*os.File)(0xc820028120), Stderr:(*os.File)(0xc820028130), ExtraFiles:[]*os.File(nil), consolePath:\"\", Capabilities:[]string(nil), ops:libcontainer.processOperations(nil)}: [8] System error: lstat /var/lib/docker/overlay/bea8f485a053939f884e145752218952af012452f4e2f0b4120edbd7f55aeb2f/merged/var/lib/rancher/convoy/convoy-gluster-750dd9cb-0c6f-4831-8815-e14fba03b618: not a directory"
15.7.2016 20:38:06time="2016-07-15T18:38:06Z" level=fatal msg="[8] System error: lstat /var/lib/docker/overlay/bea8f485a053939f884e145752218952af012452f4e2f0b4120edbd7f55aeb2f/merged/var/lib/rancher/convoy/convoy-gluster-750dd9cb-0c6f-4831-8815-e14fba03b618: not a directory"
```
so it seems to solve the initial problem but create an new one.
Any comments on solving this new Issue please post there: #134

**Comment by yasker** [comment]
Let me merge this first, and take a look at glusterfs later.

**Pull request merged**
